[client.pv.activation]
proximity = "近くで聞こえる"

[server.pv.command.list]
empty = "Plasmo Voice がインストールされているプレイヤーはいません"
message = "クライアント (%1$s/%2$s): %3$s"

[server.pv.command.mute]
already_muted = "%s は既にミュートされています"
permanently_muted = "%1$s はミュートされています。理由: %2$s"
temporarily_muted = "ミュートされた %1$s %2$s。理由: %3$s"
usage = "使い方: /vmute <player> [時間] [理由]"

[server.pv.command.mute_list]
empty = "プレイヤーがミュートされていません"
entry = "%1$s、有効期限: %2$s。理由: %3$s"
entry_muted_by = "%1$s は %2$sによってミュートされ、期限切れ: %3$s。理由: %4$s"
expiration_date = "yyyy/MM/dd"
expiration_time = "HH:mm:ss"
expire_at = "%1$s - %2$s"
header = "ミュート中のプレイヤー："
never_expires = "無制限"

[server.pv.command.reconnect]
message = "再接続パケットを送信"

[server.pv.command.reload]
message = "設定をリロードしました"

[server.pv.command.unmute]
not_muted = "%s はミュートされていません"
unmuted = "ミュート解除 %s"
usage = "使い方: /vunmute <player>"

[server.pv.error]
mod_missing_kick_message = """
申し訳ありませんが、このサーバーでプレイするには Plasmo Voice mod をインストールする必要があります。
ダウンロードはこちら: https://modrinth.com/plugin/plasmo-voice"""
no_permissions = "&c申し訳ありませんが、このコマンドを実行する権限がありません。これがエラーだと思われる場合は、サーバー管理者にお問い合わせください。"
player_not_found = "プレイヤーが見つかりません"
player_only_command = "プレイヤーだけがこのコマンドを実行できます"
version_not_supported = "申し訳ありませんが、あなたの Plasmo Voice バージョンはこのサーバーではサポートされていません。 %s"
version_not_supported_click = "サポートされているバージョンをダウンロード"
version_not_supported_hover = "%s"

[server.pv.mutes]
empty_reason = "指定なし"
permanently_muted = "ミュートされました。理由： %s"
temporarily_muted = "%1$sはミュートされました。理由： %2$s"
unmuted = "ミュート解除されました"

[server.pv.mutes.durations]
days = "%s 日"
hours = "%s 時間"
minutes = "%s 分間"
seconds = "%s 秒間"
weeks = "%s 週"
